### ISSUE TITLE
增加自定义歌词 长句功能

### ISSUE THREAD

**Issue by fengchuia** [OToNaShiAKi/material-douden-tool#4]
v有经常说的话 可以提前记录下来 还有一些原创歌曲歌词 另外弹幕捕获希望可以和其他页面同时存在

**Comment by fengchuia** [comment]
昨天用了下 歌词只能连续发 不能直接跳到某一行 非常致命 还是就是想复制指定弹幕的时候 弹幕依然在滚动 很难复制 希望可以在使用滚轮翻找弹幕的时候 保持弹幕的位置

**Comment by OToNaShiAKi** [comment]
歌词跳转是有的 鼠标滑到歌词位置时候左边那个箭头，提前记录v的话在快捷短语里

**Comment by fengchuia** [comment]
> 歌词跳转是有的 鼠标滑到歌词位置时候左边那个箭头，提前记录v的话在快捷短语里

歌词跳转看到了，快捷短语只能一个快捷键对应一句话，像是恋口上这样的长句几乎用掉了大半的快捷键

**Comment by OToNaShiAKi** [comment]
这个功能一直懒得写，因为歌词传不传挺无所谓的，下个月看吧，这个月备考所以这个项目摸鱼ing

**Comment by OToNaShiAKi** [comment]
1.1.13中已加入自制歌词~
