### ISSUE TITLE
爬取视频鉴赏动态BUG

### ISSUE THREAD

**Issue by ghost** [OToNaShiAKi/material-douden-tool#7]
爬取视频鉴赏动态输入ID后提示没有数据，版本1.1.14

**Comment by OToNaShiAKi** [comment]
哪个动态，给个id我试试，我随便找了几个没试出问题

**Comment by OToNaShiAKi** [comment]
还有一次不行多试一两次，b站时不时会拦截请求，具体原因还在研究

**Comment by ghost** [comment]
> 还有一次不行多试一两次，b站时不时会拦截请求，具体原因还在研究

找了好几个动态重试了好多次还是不行

**Comment by OToNaShiAKi** [comment]
之前想大改一下就一直拖下去了 最近有空搞了 再有一两周会连同新版一起发

**Comment by OToNaShiAKi** [comment]
1.2.0修复
